[build]
  publish = "."

[[headers]]
  for = "*.glb"
  [headers.values]
    Content-Type = "model/gltf-binary"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "*.gltf"
  [headers.values]
    Content-Type = "model/gltf+json"
    Access-Control-Allow-Origin = "*"
